language: node_js
node_js:
  - '8'
services:
  - docker
script:
  - docker build -t wsflare/ws-flare-gateway:$TRAVIS_BUILD_NUMBER .
deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push wsflare/ws-flare-gateway
    on:
      branch: master