version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - UI_URL=http://ui:80
      - WS_URL=http://websocket:8080
      - GRAPHQL_URL=http://ui:80
    volumes:
      - ./nginx/nginx.conf.tmp:/etc/nginx/nginx.conf.tmp
      - ./nginx/config.bsh:/etc/nginx/config.bsh
    command: ./etc/nginx/config.bsh
    ports:
      - 80:80
      - 443:443

  ui:
    image: nginxdemos/hello
    container_name: ui
    expose:
      - "80"

  websocket:
    image: jmalloc/echo-server
    container_name: websocket
    expose:
      - "8080"
    ports:
      - 8080:8080